---
- name: Install Apache
  hosts: your_remote_server
  become: true
  roles:
    - common
  tasks:
    - name: Install Apache package
      package:
        name: apache2
        state: present
