---
- name: Install common packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - vim
    - htop
    - unzip
    - tree

- name: Copy configuration file
  copy:
    src: files/config.ini
    dest: /etc/myapp/config.ini
    owner: root
    group: root
    mode: '0644'
